### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by ex0dus-0x** [ex0dus-0x/binsec#43]
Here are potential ideas for what to implement down the road:

* [ ] Multi-Platform Support - Windows and macOS binary security features
* [ ] Check security features on procs
* [ ] Recommended compiler flags to pass to enforce better security
* [ ] Use case - integration with automated CI/CD security pipeline to solve CTF challenges, or patch compiled unit tests.
* [ ] Potential malware detection support (integrate in YARA) ??
* [ ] Other binary security features I missed out on
